export const PRODUCTS = [
  ['cold', '코지콜 감기약', '감기약', 1800, 3500, '#ef946c', 'box', 'cold'],
  ['pain', '하루엔 진통제', '해열진통제', 1200, 2500, '#72b6c8', 'box', 'pain'],
  ['digest', '속편한 소화제', '소화제', 1400, 3000, '#79a784', 'box', 'digest'],
  ['allergy', '봄이온 알러지', '알레르기', 2000, 4000, '#b09eca', 'box', 'allergy'],
  ['patch', '포근한 파스', '파스', 2200, 4500, '#d6b66d', 'box', 'care'],
  ['band', '데일리 밴드', '상처관리', 900, 2000, '#e9b184', 'box', 'care'],
  ['vitamin', '모닝 비타민', '비타민', 6500, 12000, '#efb94d', 'bottle', 'wellness'],
  ['mask', '데일리 KF94', '마스크', 700, 1500, '#8fc9b4', 'box', 'crisis'],
  ['sanitizer', '클린 손소독제', '손소독제', 2300, 5000, '#9bbbd9', 'bottle', 'crisis'],
  ['thermo', '안심 체온계', '체온계', 10000, 18000, '#cca998', 'box', 'crisis'],
  ['tissue', '클린 티슈', '위생용품', 1000, 2200, '#b5c6ad', 'box', 'care'],
  ['kids', '키즈 비타민', '비타민', 4000, 8000, '#ecb47a', 'bottle', 'wellness'],
  ['saline', '맑은 세정액', '위생용품', 1100, 2500, '#8bbecb', 'bottle', 'care'],
  ['ointment', '케어 연고', '상처관리', 1600, 3500, '#d5a1a3', 'tube', 'care'],
  ['lozenge', '목편한 캔디', '감기약', 1300, 3000, '#a8b68a', 'box', 'cold'],
].map(([id, name, category, cost, price, color, shape, tag], i) => ({
  id,
  name,
  category,
  cost,
  price,
  color,
  shape,
  tags: [tag],
  capacity: 12,
  zone: Math.floor(i / 5),
  slot: i % 5,
}));
export const PRODUCT = Object.fromEntries(PRODUCTS.map((p) => [p.id, p]));
export const SUPPLIERS = [
  {
    id: 'standard',
    name: '한결 의약품',
    desc: '합리적인 가격 · 정기 배송',
    modifier: 1,
    delivery: 55,
    reliability: 0.98,
    limit: 100,
  },
  {
    id: 'express',
    name: '동네 퀵 도매',
    desc: '빠른 입고 · 소량 구매에 적합',
    modifier: 1.2,
    delivery: 22,
    reliability: 1,
    limit: 40,
  },
  {
    id: 'bulk',
    name: '온누리 유통',
    desc: '낮은 매입가 · 여유 있는 발주',
    modifier: 0.85,
    delivery: 95,
    reliability: 0.93,
    limit: 200,
  },
];
export const PROFILES = [
  '동네 주민',
  '회사원',
  '어르신',
  '아이를 둔 보호자',
  '단골 손님',
  '운동하는 이웃',
  '학생',
  '마스크 구매 고객',
];
export const PRESCRIPTIONS = Array.from({ length: 10 }, (_, i) => ({
  id: `rx${i}`,
  name: ['일반 처방', '소아 처방', '정기 처방', '복합 처방', '간단 처방'][i % 5],
  duration: 4 + i * 0.5,
  reward: 6500 + i * 600,
  cost: 1800 + i * 170,
}));
export const POPS = [
  {
    id: 'mask',
    name: '마스크 품절 안내',
    text: '마스크 품절',
    desc: '마스크가 없을 때 반복 문의 70% 감소',
    price: 15000,
  },
  {
    id: 'limit',
    name: '1인 3개 한정',
    text: '1인 3개',
    desc: '위기 시 대량 구매 수요 완화',
    price: 15000,
  },
  {
    id: 'cold',
    name: '감기약 이쪽',
    text: '감기약 →',
    desc: '상품 탐색 시간 35% 감소',
    price: 12000,
  },
  {
    id: 'rx',
    name: '처방전 접수 안내',
    text: '처방 접수',
    desc: '처방 고객 인내심 20% 증가',
    price: 18000,
  },
  {
    id: 'checkout',
    name: '계산 대기 안내',
    text: '한 줄 서기',
    desc: '계산 고객 인내심 15% 증가',
    price: 12000,
  },
  {
    id: 'kids',
    name: '어린이 제품 안내',
    text: '어린이용',
    desc: '상담 시간 15% 감소',
    price: 12000,
  },
  { id: 'hygiene', name: '손 위생 안내', text: '손 소독', desc: '방문 경험 향상', price: 10000 },
  {
    id: 'hours',
    name: '영업시간 안내',
    text: '09–18 OPEN',
    desc: '전화 문의 30% 감소',
    price: 10000,
  },
];
export const NEWS = [
  '오늘도 문을 엽니다. 우리 동네의 건강한 하루.',
  '차가운 날씨, 동네 감기약 수요 소폭 증가',
  '해외 원인불명 호흡기 질환 소식… 시민 관심 늘어',
  '예방용품을 찾는 발길, 마스크 문의 증가',
  '마스크 주문 증가… 일부 도매상 배송 지연',
  '위생용품 수요 급증, 안정적인 재고 확보 필요',
  '마스크 공급 부족 지속… 동네약국 대기줄 늘어',
  '구매 수량 안내로 혼잡을 줄이는 약국들',
  '공급업체, 생산량 확대… 회복까지 시간 필요',
  '예방용품 공급 정상화 시작',
  '마스크 입고량 증가, 남는 재고에 주의',
  '동네약국 운영 점차 일상 회복',
  '봄철 알레르기 제품 관심 증가',
  '건강 관리의 시작, 이웃 약국과 상담하세요',
  '오늘도 수고했어요. 내일도 함께하는 동네약국',
];
export const ZONES = [
  { x: -4.15, z: 1.4, label: '데일리 케어', color: '#8ba789' },
  { x: 4, z: -1.6, label: '건강한 일상', color: '#dba46f' },
  { x: 4, z: 1.3, label: '생활 · 위생', color: '#81aca7' },
];
export const BLOCKS = [
  { x: -2.4, z: -0.85, w: 4.8, d: 0.9 },
  { x: -4.15, z: 1.4, w: 2.1, d: 0.8 },
  { x: 4, z: -1.6, w: 2.15, d: 0.8 },
  { x: 4, z: 1.3, w: 2.15, d: 0.8 },
  { x: -3.4, z: -3.6, w: 4.4, d: 0.7 },
  { x: 3.4, z: -3.65, w: 3.8, d: 0.65 },
];
export const SPOTS = {
  entry: { x: 1.5, z: 5.7 },
  door: { x: 1.5, z: 3.9 },
  checkout: { x: -0.7, z: -1.6 },
  rx: { x: -3.5, z: -1.6 },
  cabinet: { x: -4, z: -2.7 },
  compound: { x: -2.3, z: -2.7 },
  storage: { x: 3, z: -2.7 },
  delivery: { x: 4.7, z: 2.8 },
  phone: { x: -0.5, z: -2.7 },
};
export const ROLES = {
  cashier: {
    name: '계산 직원',
    salary: 60000,
    cost: 180000,
    types: ['checkout', 'delivery', 'restock'],
  },
  pharmacist: {
    name: '근무 약사',
    salary: 140000,
    cost: 350000,
    types: ['checkout', 'prescription', 'consult', 'phone', 'delivery', 'restock'],
  },
  stocker: { name: '재고 직원', salary: 50000, cost: 150000, types: ['delivery', 'restock'] },
};
