// Fictional campaign balance. All multipliers are relative to ordinary trading.
const stage = (name, demand, traffic, cost, delivery, supply, advice) => ({
  name,
  demand,
  traffic,
  cost,
  delivery,
  supply,
  advice,
});
export const CRISIS_STAGES = [
  stage('평온한 일상', 1, 1, 1, 1, 1, '기본 재고를 채우고 직원의 업무를 익혀두세요.'),
  stage('첫 경계', 1.2, 1.1, 1.05, 1.1, 0.9, '마스크와 손소독제 재고를 확인하세요.'),
  stage('문의 증가', 1.6, 1.25, 1.12, 1.25, 0.8, '품절 안내 POP로 반복 문의를 줄여보세요.'),
  stage(
    '수요 급증',
    2.5,
    1.5,
    1.25,
    1.5,
    0.65,
    '배송이 느려집니다. 남은 재고가 있을 때 발주하세요.',
  ),
  stage(
    '공급 부족',
    3.2,
    1.75,
    1.4,
    1.8,
    0.5,
    '공급업체별 남은 물량을 비교하고 입고 업무를 분담하세요.',
  ),
  stage('위기의 정점', 4, 2, 1.6, 2.2, 0.35, '계산과 조제를 분담하고 대기 안내를 설치하세요.'),
  stage(
    '증산 시작',
    2.8,
    1.7,
    1.4,
    1.8,
    0.5,
    '공급은 아직 부족합니다. 당일 필요한 물량부터 확보하세요.',
  ),
  stage(
    '공급 회복',
    1.8,
    1.4,
    1.2,
    1.4,
    0.75,
    '내일 수요가 크게 줄어듭니다. 과잉 발주를 줄이세요.',
  ),
  stage(
    '수요 반락',
    0.7,
    1.1,
    1.05,
    1.1,
    0.95,
    '남은 위생용품을 먼저 진열하고 창고 여유를 확보하세요.',
  ),
  stage('일상 회복', 1, 1, 1, 1, 1, '공급과 방문량이 정상화되었습니다. 약국 운영을 이어가세요.'),
];
export const stageForDay = (day) => Math.max(0, Math.min(9, day - 3));
